@echo off
setlocal enabledelayedexpansion

rem ============================================================================
rem  DL Pixel Classifier - Python Server Setup
rem
rem  Usage:
rem    setup_server.bat                        (venv in python_server\venv)
rem    setup_server.bat F:\dl-classifier-env   (venv at custom path)
rem    setup_server.bat --cuda                 (default path, with CUDA)
rem    setup_server.bat F:\dl-env --cuda       (custom path, with CUDA)
rem ============================================================================

set "SCRIPT_DIR=%~dp0"
set "SERVER_DIR=%SCRIPT_DIR%python_server"
set "VENV_PATH="
set "USE_CUDA=0"
set "CONFIG_FILE=%SCRIPT_DIR%.server_config"

rem Parse arguments
:parse_args
if "%~1"=="" goto done_args
if /i "%~1"=="--cuda" (
    set "USE_CUDA=1"
    shift
    goto parse_args
)
if /i "%~1"=="--help" goto show_help
if /i "%~1"=="-h" goto show_help
rem Treat as venv path
set "VENV_PATH=%~1"
shift
goto parse_args
:done_args

rem Default venv path
if "%VENV_PATH%"=="" set "VENV_PATH=%SERVER_DIR%\venv"

echo.
echo  DL Pixel Classifier - Server Setup
echo  ===================================
echo.
echo  Server source: %SERVER_DIR%
echo  Virtual env:   %VENV_PATH%
if "%USE_CUDA%"=="1" (echo  GPU support:   CUDA) else (echo  GPU support:   CPU only)
echo.

rem Check Python is available
python --version >nul 2>&1
if errorlevel 1 (
    echo  ERROR: Python not found in PATH.
    echo  Install Python 3.10+ from https://www.python.org/downloads/
    echo  Make sure to check "Add Python to PATH" during installation.
    exit /b 1
)

rem Show Python version
for /f "tokens=*" %%i in ('python --version 2^>^&1') do set "PY_VER=%%i"
echo  Found: %PY_VER%
echo.

rem Create virtual environment
if exist "%VENV_PATH%\Scripts\activate.bat" (
    echo  Virtual environment already exists at %VENV_PATH%
    set /p RECREATE="  Recreate it? (y/N): "
    if /i "!RECREATE!"=="y" (
        echo  Removing old environment...
        rmdir /s /q "%VENV_PATH%"
    ) else (
        echo  Reusing existing environment.
        goto install_deps
    )
)

echo  Creating virtual environment at %VENV_PATH% ...
python -m venv "%VENV_PATH%"
if errorlevel 1 (
    echo  ERROR: Failed to create virtual environment.
    exit /b 1
)
echo  Virtual environment created.

:install_deps
echo.
echo  Activating environment and installing dependencies...
echo  (This may take several minutes for PyTorch download)
echo.

call "%VENV_PATH%\Scripts\activate.bat"

rem Upgrade pip first
python -m pip install --upgrade pip >nul 2>&1

rem Install the server package
if "%USE_CUDA%"=="1" (
    echo  Installing with CUDA support...
    pip install -e "%SERVER_DIR%[cuda]"
) else (
    echo  Installing CPU-only...
    pip install -e "%SERVER_DIR%"
)

if errorlevel 1 (
    echo.
    echo  ERROR: Installation failed. Check the output above.
    exit /b 1
)

rem Save config so start_server.bat knows where the venv is
echo VENV_PATH=%VENV_PATH%> "%CONFIG_FILE%"
echo SERVER_DIR=%SERVER_DIR%>> "%CONFIG_FILE%"

rem Create start_server.bat
echo @echo off> "%SCRIPT_DIR%start_server.bat"
echo rem Auto-generated by setup_server.bat>> "%SCRIPT_DIR%start_server.bat"
echo call "%VENV_PATH%\Scripts\activate.bat">> "%SCRIPT_DIR%start_server.bat"
echo echo Starting DL Pixel Classifier server...>> "%SCRIPT_DIR%start_server.bat"
echo echo Press Ctrl+C to stop.>> "%SCRIPT_DIR%start_server.bat"
echo echo.>> "%SCRIPT_DIR%start_server.bat"
echo dlclassifier-server>> "%SCRIPT_DIR%start_server.bat"

echo.
echo  ===================================
echo  Setup complete!
echo  ===================================
echo.
echo  To start the server:
echo    start_server.bat
echo.
echo  Or manually:
echo    "%VENV_PATH%\Scripts\activate.bat"
echo    dlclassifier-server
echo.

rem Quick GPU check
echo  Checking GPU availability...
python -c "import torch; print(f'  PyTorch {torch.__version__}'); print(f'  CUDA available: {torch.cuda.is_available()}'); print(f'  Device: {torch.cuda.get_device_name(0)}' if torch.cuda.is_available() else '  (CPU mode)')"
echo.

rem Ask if user wants to start server now
set /p START_NOW="  Start server now? (Y/n): "
if /i "!START_NOW!"=="n" goto end
echo.
dlclassifier-server

:end
endlocal
exit /b 0

:show_help
echo.
echo  Usage: setup_server.bat [VENV_PATH] [--cuda]
echo.
echo  Arguments:
echo    VENV_PATH    Path for the virtual environment (default: python_server\venv)
echo    --cuda       Install with NVIDIA CUDA GPU support
echo.
echo  Examples:
echo    setup_server.bat                              Default location, CPU
echo    setup_server.bat --cuda                       Default location, CUDA
echo    setup_server.bat F:\dl-classifier-env         Custom path, CPU
echo    setup_server.bat F:\dl-classifier-env --cuda  Custom path, CUDA
echo.
exit /b 0
