#!/bin/bash
# ===========================================================================
#  DL Pixel Classifier - Python Server Setup
#
#  Usage:
#    ./setup_server.sh                         (venv in python_server/venv)
#    ./setup_server.sh /fast/dl-env            (venv at custom path)
#    ./setup_server.sh --cuda                  (default path, with CUDA)
#    ./setup_server.sh /fast/dl-env --cuda     (custom path, with CUDA)
# ===========================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_DIR="$SCRIPT_DIR/python_server"
VENV_PATH=""
USE_CUDA=0
CONFIG_FILE="$SCRIPT_DIR/.server_config"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --cuda)    USE_CUDA=1; shift ;;
        --help|-h)
            echo ""
            echo "Usage: $0 [VENV_PATH] [--cuda]"
            echo ""
            echo "  VENV_PATH    Path for the virtual environment (default: python_server/venv)"
            echo "  --cuda       Install with NVIDIA CUDA GPU support"
            echo ""
            echo "Examples:"
            echo "  $0                              # Default location, CPU"
            echo "  $0 --cuda                       # Default location, CUDA"
            echo "  $0 /fast/dl-env                 # Custom path, CPU"
            echo "  $0 /fast/dl-env --cuda          # Custom path, CUDA"
            echo ""
            exit 0
            ;;
        *)         VENV_PATH="$1"; shift ;;
    esac
done

# Default venv path
if [ -z "$VENV_PATH" ]; then
    VENV_PATH="$SERVER_DIR/venv"
fi

echo ""
echo " DL Pixel Classifier - Server Setup"
echo " ==================================="
echo ""
echo " Server source: $SERVER_DIR"
echo " Virtual env:   $VENV_PATH"
if [ "$USE_CUDA" -eq 1 ]; then
    echo " GPU support:   CUDA"
else
    echo " GPU support:   CPU only"
fi
echo ""

# Check Python
if ! command -v python3 &>/dev/null; then
    echo " ERROR: python3 not found. Install Python 3.10+."
    exit 1
fi

python3 --version

# Create virtual environment
if [ -d "$VENV_PATH" ] && [ -f "$VENV_PATH/bin/activate" ]; then
    echo " Virtual environment already exists at $VENV_PATH"
    read -p " Recreate it? (y/N): " RECREATE
    if [[ "$RECREATE" =~ ^[Yy]$ ]]; then
        echo " Removing old environment..."
        rm -rf "$VENV_PATH"
    else
        echo " Reusing existing environment."
    fi
fi

if [ ! -d "$VENV_PATH" ]; then
    echo " Creating virtual environment at $VENV_PATH ..."
    python3 -m venv "$VENV_PATH"
    echo " Virtual environment created."
fi

echo ""
echo " Installing dependencies..."
echo ""

source "$VENV_PATH/bin/activate"
pip install --upgrade pip > /dev/null 2>&1

if [ "$USE_CUDA" -eq 1 ]; then
    echo " Installing with CUDA support..."
    pip install -e "$SERVER_DIR[cuda]"
else
    echo " Installing CPU-only..."
    pip install -e "$SERVER_DIR"
fi

# Save config
cat > "$CONFIG_FILE" <<CONF
VENV_PATH=$VENV_PATH
SERVER_DIR=$SERVER_DIR
CONF

# Create start script
cat > "$SCRIPT_DIR/start_server.sh" <<LAUNCHER
#!/bin/bash
# Auto-generated by setup_server.sh
source "$VENV_PATH/bin/activate"
echo "Starting DL Pixel Classifier server..."
echo "Press Ctrl+C to stop."
echo ""
dlclassifier-server
LAUNCHER
chmod +x "$SCRIPT_DIR/start_server.sh"

echo ""
echo " ==================================="
echo " Setup complete!"
echo " ==================================="
echo ""
echo " To start the server:"
echo "   ./start_server.sh"
echo ""

# GPU check
python3 -c "import torch; print(f' PyTorch {torch.__version__}'); print(f' CUDA: {torch.cuda.is_available()}'); print(f' Device: {torch.cuda.get_device_name(0)}' if torch.cuda.is_available() else ' (CPU mode)')" 2>/dev/null || echo " (PyTorch GPU check skipped)"
echo ""

read -p " Start server now? (Y/n): " START_NOW
if [[ ! "$START_NOW" =~ ^[Nn]$ ]]; then
    dlclassifier-server
fi
